name: Security SAST scan (Detect vulnerabilities)

on:
  pull_request:
    branches:
      - main
      - develop
      - preprod

jobs:
  semgrep:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:

      - name: 🧪 List files 1
        run: ls -la

      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install semgrep and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semgrep
          semgrep --version
      
      - name: 🧪 List files 2
        run: ls -la

      - name: 🆔 Generate unique and random string for unique file naming
        run: echo "UNIQ_STR=$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 30)" >> "$GITHUB_ENV"

      - name: 🫙 Store Perso Git URL in environment variable
        run: echo "PERSO_GIT=https://github.com/Naim-Aouaichia/" >> "$GITHUB_ENV"

      - name: 🚀🪲 Run semgrep for scan low vulnerabilities levels and add severity result in report
        run: |
          semgrep --config=auto . \
            --sarif --sarif-output="output-${UNIQ_STR}-info.json" --severity=INFO

          jq '.runs[].results[] |= (.properties["security-severity"] = "1.0")' \
            "output-${UNIQ_STR}-info.json" > "output-${UNIQ_STR}-info.sarif"

      - name: 🚀🪲🪲 Run semgrep for scan medium vulnerabilities levels and add severity result in report
        run: |
          semgrep --config=auto . \
            --sarif --sarif-output="output-${UNIQ_STR}-warning.json" --severity=WARNING

          jq '.runs[].results[] |= (.properties["security-severity"] = "5.0")' \
            "output-${UNIQ_STR}-warning.json" > "output-${UNIQ_STR}-warning.sarif"

      - name: 🚀🪲🪲🪲 Run semgrep for scan high vulnerabilities levels and add severity result in report
        run: |
          semgrep --config=auto . \
            --sarif --sarif-output="output-${UNIQ_STR}-error.json" --severity=ERROR

          jq '.runs[].results[] |= (.properties["security-severity"] = "7.0")' \
            "output-${UNIQ_STR}-error.json" > "output-${UNIQ_STR}-error.sarif"

      - name: 🔗 Aggregate result in semgrep-report-temp.sarif
        run: |
          jq -s '{
            version: (.[0].version),
            runs: [
              {
                invocations: (map(.runs[].invocations) | add),
                results: (map(.runs[].results) | add),
                tool: {
                  driver: {
                    name: (.[0].runs[0].tool.driver.name),
                    rules: (map(.runs[].tool.driver.rules) | add),
                    semanticVersion: (.[0].runs[0].tool.driver.semanticVersion)
                  }
                }
              }
            ],
            "$schema": (.[0]."$schema")
          }' "output-${UNIQ_STR}-"*.sarif > semgrep-report-temp.sarif

      - name: 💾 Format sarif file as required
        id: report_prep
        run: |
          echo "********* Change driver name"
          jq '.runs[0].tool.driver.name = "Semgrep"' semgrep-report-temp.sarif > semgrep-report-temp-temp.sarif
          echo "********* Set right severity code for GHAS"
          jq '.runs[0].tool.driver.rules |= map(
            if .defaultConfiguration.level == "note" then .properties.severity = "MEDIUM"
            elif .defaultConfiguration.level == "warning" then .properties.severity = "HIGH"
            elif .defaultConfiguration.level == "error" then .properties.severity = "CRITICAL"
            else . end
          )' semgrep-report-temp-temp.sarif > semgrep-report-temp.sarif
          echo "********* Delete old severity code, avoiding polluting vuln reports with bad code"
          jq '.runs[0].tool.driver.rules |= map(
            del(.defaultConfiguration)
          )' semgrep-report-temp.sarif > semgrep-report.sarif
          echo "********* Prepare security tab code scanning link"
          echo "tab_security_github=${{ env.PERSO_GIT }}${{ github.event.repository.name }}/security/code-scanning" >> "$GITHUB_OUTPUT"

      - name: ⬆️ Upload Semgrep file as SARIF to GitHub Advanced Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
          category: semgrep-sast-analysis
          checkout_path: .
          ref: refs/heads/main

      - name: 🔄 Count and store vuln
        run: |
          jq '.runs[0].results | length' semgrep-report.sarif > vuln_count.txt
          VULN_COUNT=$(cat vuln_count.txt)
          echo "Nombre de vulnérabilités détectées : $VULN_COUNT"
          echo "VULN_COUNT=$VULN_COUNT" >> $GITHUB_ENV

      - name: 🧪 List files 3
        run: ls -la

      - name: ✅ Vérification du résultat de l’analyse
        run: |
          if [ "${VULN_COUNT}" -gt 0 ]; then
            echo "❌ ${VULN_COUNT} vulnérabilités détectées. CI bloquée."
            exit 1
          else
            echo "✅ Aucune vulnérabilité détectée. CI validée."
          fi